"""Generate `docs/FIELD_CATALOG.md` from the extractor's own specs.

The catalog is the one vocabulary `invoice_extractor` and `invoice_forge` share: the
canonical field names, what each value is typed as, and how it is normalised. It is
derived, never typed by hand — `tests/test_field_catalog_matches_extractor.py` fails
when this file and the specs disagree, and the fix is always to regenerate.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Iterator, Mapping
from pathlib import Path

from invoice_extractor.domain.models import VALUE_TYPES, LineItem
from invoice_extractor.extraction.normalizers import (
    parse_date,
    parse_money,
    parse_percent,
    strip_label,
    upper_alnum,
)
from invoice_extractor.extraction.spec import Normalizer
from invoice_extractor.extraction.specs import FIELD_SPECS
from invoice_extractor.layout.schema import LINE_ITEM_COLUMNS

CATALOG_PATH = Path("docs/FIELD_CATALOG.md")

# Where on an invoice each value belongs. The specs do not say, so the catalog does.
KINDS: Mapping[str, str] = {
    "invoice_number": "scalar",
    "invoice_date": "scalar",
    "due_date": "scalar",
    "supplier_vat_id": "party",
    "customer_vat_id": "party",
    "currency": "scalar",
    "vat_rate": "totals",
    "subtotal": "totals",
    "vat_amount": "totals",
    "total_amount": "totals",
}

NORMALISATION: Mapping[Normalizer, str] = {
    strip_label: "the text after the label's colon, stripped",
    parse_date: "an ISO-8601 date",
    parse_money: "a plain decimal string, the layout's separators removed",
    parse_percent: "a plain decimal string, a trailing percent sign removed",
    upper_alnum: "letters and digits only, upper-cased",
}

COLUMN_NORMALISATION: Mapping[str, str] = {
    "str": "the cell's text, stripped",
    "Decimal": "a plain decimal string, the layout's separators removed",
}

HEADER = """# Field catalog

The canonical field names `invoice_extractor` and `invoice_forge` share. The extractor
declares them in `extraction/specs.py` and `layout/schema.py`; the generator writes one
truth entry under each name (`docs/GROUND_TRUTH_SCHEMA.md`), and the benchmark compares
name by name. A name the extractor does not know yet is reported as "not covered",
never as wrong.

Generated by `python scripts/make_field_catalog.py`. Do not edit this file by hand:
`tests/test_field_catalog_matches_extractor.py` fails when it and the specs disagree,
and the fix is to change the specs and regenerate.
"""

SCALAR_INTRO = """
## Scalar fields

`Kind` says where on an invoice the value belongs: `scalar` for the document's own
identifiers and dates, `party` for a value that describes the supplier or the customer,
`totals` for the money block at the foot of the document.
"""

COLUMN_INTRO = """
## Line-item columns

Every row of the line-item table carries these five columns, in this order. They are
the fields of `LineItem`, so the table and the record cannot drift apart.
"""

TABLE_HEAD = "\n| Field | Kind | Value type | Normalised to |\n|---|---|---|---|\n"

Row = tuple[str, str, str, str]


def scalar_rows() -> list[Row]:
    """One row per `FieldSpec`, in the order the extractor reports them."""
    return [
        (
            spec.name,
            KINDS[spec.name],
            VALUE_TYPES[spec.name].__name__,
            NORMALISATION[spec.normalizer],
        )
        for spec in FIELD_SPECS
    ]


def column_rows() -> list[Row]:
    """One row per line-item column, typed from the `LineItem` record itself."""
    types = {field.name: str(field.type) for field in dataclasses.fields(LineItem)}
    return [
        (column, "table", types[column], COLUMN_NORMALISATION[types[column]])
        for column in LINE_ITEM_COLUMNS
    ]


def _table(rows: list[Row]) -> str:
    body = "".join(
        f"| `{name}` | {kind} | `{value}` | {rule} |\n" for name, kind, value, rule in rows
    )
    return f"{TABLE_HEAD}{body}"


def sections() -> Iterator[str]:
    """The catalog, section by section, so `main` can append rather than accumulate."""
    yield HEADER
    yield SCALAR_INTRO
    yield _table(scalar_rows())
    yield COLUMN_INTRO
    yield _table(column_rows())


def catalog_markdown() -> str:
    return "".join(sections())


def main() -> None:
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CATALOG_PATH.open("w", encoding="utf-8") as catalog:
        for section in sections():
            catalog.write(section)


if __name__ == "__main__":
    main()
